server:
  port: 18081
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D"
      max-days: 7
      rotate: true
    basedir: .
  servlet:
    encoding:
      charset: utf-8
      force: true

app:
  slack:
    url: 'test'